spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:13306/tx_db
#    user-name: root
#    password: 123456


  kafka:
    bootstrapServers:
      - 127.0.0.1:9092
    producer:
      acks: 1
      retries: 3
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer